// Cocktails
export const FETCH_COCKTAILS_START = 'FETCH_COCKTAILS_START';
export const FETCH_COCKTAILS_SUCCESS = 'FETCH_COCKTAILS_SUCCESS';
export const FETCH_COCKTAILS_ERROR = 'FETCH_COCKTAILS_ERROR';